### ISSUE TITLE
Intent to Migrate: WebCodecs

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/webcodecs#130]
## Intent to Migrate: WebCodecs

Hi all,

I'm sending this as Media WG co-chair, following approval from @padenot and @chcunningham (editors)
cc @jernoble @tidoust as respectively co-chair and W3C contact of the Media Working Group.

The [Media Working Group](https://www.w3.org/media-wg/) is ready to adopt WebCodecs as a W3C Recommendation track deliverable.

### Working group decision to adopt

See the [charter of the Media Working Group](https://www.w3.org/2019/05/media-wg-charter.html#deliverables) including "encoders/decoders API" work.

A CfC to adopt the specification formally by the group members as a FPWD was sent: https://lists.w3.org/Archives/Public/public-media-wg/2021Feb/0000.html

### Proposal

Latest [WebCodecs draft](https://wicg.github.io/web-codecs/) ([Git repo](https://github.com/WICG/web-codecs/))

### Summary

API that allows web applications to encode and decode audio and video

### Motivation and Use Cases

Detailed in the [explainer](https://github.com/WICG/media-capabilities/blob/master/explainer.md)

### Compatibility Risk

There is no obvious compatibility risks. WebCodecs has wide support from browsers and web developers. New features to help support new use cases should be added but none are expected to be require major changes.

### Ongoing technical constraints

Some capabilities depend on the underlying hardware (hardware decode/encode) but can be supported in software for the cost of lower performance.

### Link to implementation experience and demos

This blog post demonstrates video encoding, decoding, and rendering.
https://web.dev/webcodecs/

This demo demonstrates video decoding and rendering of Big Buck Bunny.
https://tguilbert-google.github.io/webcodecs/mp4/index.html

### Data

No quantified data at the moment but very strong positive feedback from web developers.

### Security and Privacy

See [responses to security and privacy questionnaire](https://github.com/WICG/web-codecs/blob/master/security-privacy-questionnaire.md).

### Accessibility

No direct accessibility implications known at this stage.

### Internationalization

No internationalization implications so far.

**Comment by tidoust** [comment]
The Media WG [resolved to adopt WebCodecs as a WG deliverable](https://lists.w3.org/Archives/Public/public-media-wg/2021Mar/0004.html). I will transition the repository to w3c accordingly.

**Comment by tidoust** [comment]
Practical transition steps:

- [ ] Update [CONTRIBUTING.md](https://github.com/WICG/web-codecs/blob/main/CONTRIBUTING.md) to match that used in W3C
- [ ] Update [LICENSE.md](https://github.com/WICG/web-codecs/blob/main/LICENSE.md) to drop the CLA part
- [ ] Update links in [README.md](https://github.com/WICG/web-codecs/blob/main/README.md) and to mention Media WG
- [ ] Update [w3c.json](https://github.com/WICG/web-codecs/blob/main/w3c.json)
- [ ] Update status, group, and links that currently target the WICG repo in the [spec itself](https://github.com/WICG/web-codecs/blob/main/index.src.html)
- [ ] Transition the repo to the `w3c` org
- [ ] Make sure that editors have the right maintain rights on the new repo
- [ ] Make sure that [repo manager](https://labs.w3.org/repo-manager/) is aware that the spec has been adopted by the Media WG
- [ ] Make sure that Travis CI configuration gets migrated properly (and/or use the opportunity to switch to spec-prod, since that will be needed to automate the publication afterwards)
- [ ] Update link in About section of GitHub repo
- [ ] Add `web-codecs` folder and redirect under [wicg.github.io](https://github.com/WICG/wicg.github.io)

**Comment by tidoust** [comment]
Repo and spec successfully migrated to the Media WG. All previous links to spec, repo, issues and pull requests should be automatically redirected to the new repo. Please create an issue if you spot something wrong!
