### ISSUE TITLE
Use still images on canvas in webcodecs example

### ISSUE THREAD

**Issue by fnandoz21** [w3c/webcodecs#144]
I am trying to figure out how to incorporate images, such as those captured from a video, and use them in a similar way to the webcodecs example found [here](https://webcodecs-blogpost-demo.glitch.me/). I have run into issues with using drawImage on the canvas, as this does not seem to trigger the VideoTrackReader in the way that the example does. If someone could help with this, I would really appreciate it. I pretty much have all of the same code as the example, except that my startDrawing function is different, where I loop through a folder of images/frames, shown here: 

`
 async function startDrawing() {
        let cnv = document.getElementById("src");
        var ctx = cnv.getContext("2d", { alpha: false });

        let drawOneFrame = function (time) {
          let idx = (parseInt(time / 20, 10) % 317) + 1;

          base_image = new Image();
          base_image.src = "images_60/out" + idx.toString() + ".png";
          base_image.onload = function () {
            ctx.drawImage(base_image, 0, 0);
          };
          window.requestAnimationFrame(drawOneFrame);
        };
        window.requestAnimationFrame(drawOneFrame);
      }
`

**Comment by tguilbert-google** [comment]
From a quick glance (but I'm really not a JS expert, so this might be wrong), since you are drawing in `onload()` and not in `window.rAF`, you will not achieve a guaranteed smooth 1 new image per frame. E.g. a image could take a long time to load, and then two images will be loaded/drawn at once, or none at all.

Also, if you are using `base_image = new Image()` instead of `var base_image = new Image()`, it's possible that by the time that `onload()` is called, `base_image` will have a different value, and you will try to draw the latest (possibly not loaded) image.

You should try pre-loading your images into some sort of queue or map, and then drawing 1 of them directly inside the `window.rAF` call.

**Comment by padenot** [comment]
I think @tguilbert-google's explanation is clear, I'm closing this as this isn't really related to the specification process. Thanks!
