### ISSUE TITLE
timestamp -> timeStamp?

### ISSUE THREAD

**Issue by domenic** [w3c/webcodecs#156]
Spinning off from https://github.com/WICG/web-codecs/issues/122... other places on the web platform use "time stamp" or `timeStamp` when in API form. Most notably, https://dom.spec.whatwg.org/#dom-event-timestamp .

It's probably a good idea to stay consistent with the rest of the platform in this regard, and use `timeStamp` (or `timeStampMicroseconds`) instead of `timestamp` or `timestepMicroseconds`

**Comment by chcunningham** [comment]
I do think [timestamp is more common](https://books.google.com/ngrams/graph?content=timestamp%2Ctime+stamp&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Ctimestamp%3B%2Cc0%3B.t1%3B%2Ctime%20stamp%3B%2Cc0#t1%3B%2Ctimestamp%3B%2Cc0%3B.t1%3B%2Ctime%20stamp%3B%2Cc0), but changing for consistency SGTM. I'll block on resolution of #122 (hopefully soon).

**Comment by chrisn** [comment]
I note that Media Source Extensions uses [`timestamp`](https://w3c.github.io/media-source/#dom-sourcebuffer-timestampoffset), and Web Audio has [AudioTimestamp](https://webaudio.github.io/web-audio-api/#AudioTimestamp), so I'd suggest lowercase timestamp would be consistent with the parts of the platform that handle audio and video.

**Comment by cwilso** [comment]
I would note neither of those places uses "timestamp" as a variable name - in MSE, it's "start" and "end" and "timestampOffset" (the best proof of your point).  In WebAudio, AudioTimestamp is a type - but you would use "getOutputTimestamp()", so kinda similar, but usually times are "start" and "end" and the like.  By contrast, though, the DOMEvent "timeStamp" attribute is used pretty much everywhere (because most things that have associated time are events - or rather, Events - which have this attribute inherited).  Web MIDI code, for example, will regularly refer to ".timeStamp" for MIDI events.

**Comment by dogben** [comment]
It's spelled "timestamp" throughout the WebRTC spec, e.g. [RTCRtpContributingSource](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcontributingsource-timestamp), [RTCStats](https://w3c.github.io/webrtc-pc/#dom-rtcstats-timestamp), and throughout [Identifiers for WebRTC's Statistics API](https://www.w3.org/TR/webrtc-stats/).

It's also "timestamp" in the [Generic Sensor API](https://www.w3.org/TR/generic-sensor/#sensor-timestamp) spec, the [Notifications API](https://notifications.spec.whatwg.org/#dom-notification-timestamp) and a few other specs in earlier stages.

I would argue that Event.timeStamp and the type names DOMTimeStamp and DOMHighResTimeStamp are the outliers here.

**Comment by chcunningham** [comment]
we find the points about timestamp (no 'S') in other media apis compelling. editors resolved to keep it 'timestamp'
