### ISSUE TITLE
Event listener for encodeQueueSize changes

### ISSUE THREAD

**Issue by sbalko** [w3c/webcodecs#280]
Detecting changes in the value of VideoEncoder's encodeQueueSize property currently requires some sort of polling logic. 

Could there instead be some event listener capability built into VideoEncoder? I.e. an "encodequeuesizechange" event that application code can subscribe to in order to throttle or speed up feeding more frames into encode().

**Comment by sandersdan** [comment]
Backpressure for codecs is something that's been only minimally designed so far. Events for changes are missing, as are signals other than queue size (which is an indirect measure). Improvements probably won't happen in WebCodecs v1 but it's certainly known to be an area that is lacking and should get attention in v2.

For this specific request, an event does make sense. As long as the event message doesn't carry any state, the only real risk is the event being received after the codec has changed state (eg. failed due to an error). As long as apps handle that, as they should already be doing for the `flush()` promise, it seems unlikely to create unexpected complexity / edge cases.

**Comment by sbalko** [comment]
Thanks for acknowledging our use-case. 

We are currently working around this problem by doing some `setTimeout` based asynchronous "polling" of `encodeQueueSize` enforcing a small and hard-coded limit before we call `encode` again. The solution you describe would be perfectly acceptable, ie., there is no need to synchronize the event handler with further codec state changes.

**Comment by chcunningham** [comment]
Plan SGTM

**Comment by chcunningham** [comment]
p1 since polling is bad and this is trivial to fix
