### ISSUE TITLE
decode() tolerance to reordering

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#302]
Currently `VideoDecoder.decode(chunk)` (or `AudioDecoder.decode(chunk)` for that matter) does not describe how WebCodecs handles chunks provided out-of-order.

For example, when using a partially reliable transport (e.g. QUIC reliable streams with a timer set after which a RESET is sent), encoded chunks can be transported on separate streams. In such a situation, chunks may not be received in order (e.g. a later encoded frame might not encounter loss and so might be wholly received before an earlier frame has recovered from loss).  Can encoded chunks be fed to WebCodecs decoder in the order in which they were received, or is the application expected to maintain ordering on its own? 

If feeding chunks to `decode()` out of order is allowed, how much reordering can the application expect a WebCodecs implementation to tolerate?

**Comment by sandersdan** [comment]
I did not intend for the WebCodecs decoders to support out-of-order input. I also don't think that's a common thing for decoder interfaces to offer?

There is no requirement that input or output timestamps are increasing, or for decoders to detect and reject out-of-order input. You are likely to get corruption or a decode error.

**Comment by aboba** [comment]
@sandersdan Agree that it is not common for decoder interfaces to support out-of-order input. So I was surprised to see the `decode()` text not addressing this.  If some implementations allowed reordering and others did not, this would represent an interop problem, so a WPT test confirming the recommended behavior would make sense.

**Comment by sandersdan** [comment]
> a WPT test confirming the recommended behavior would make sense.

That's reasonable, but I'm not really sure how to do that. I don't think there are any codec-agnostic tests that could verify the intended behavior, and we don't specify the behavior of specific codecs precisely enough to write tests against. In general codecs are allowed to implement error recovery mechanisms so even clearly invalid streams are not necessarily possible to detect.

There actually is a corrupt decode test case in the WPT already (https://github.com/web-platform-tests/wpt/blob/master/webcodecs/videoDecoder-codec-specific.any.js#L381), but it will probably have to be removed because no simple intentional corruption we have tried has universally forced decoders to emit decode errors.

**Comment by padenot** [comment]
It seems to me, considering the low-level nature of the API, that it's on authors to give a valid byte stream as input of the decoder. As @sandersdan says, this will (probably?) just error out, like some native decoder do.

On the other hand, https://github.com/w3c/webcodecs/issues/302#issuecomment-880970470 is likely to become a problem, especially considering implementations that don't really have the choice of decoder to use: Gecko, Safari/WebKit, to implement patented formats, everybody when there's something platform specific for hardware acceleration.

**Comment by chcunningham** [comment]
Editors call: We're in agreement on behavior, just need a spec update to clarify that this is how it works.
