### ISSUE TITLE
why is the frame's format is null

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#391]
https://glitch.com/edit/#!/new-webcodecs-blogpost-demo

In this demo , in the `handleFrame` function ,the frame's format is null , so what is format ? I420 ? OR BGRA ?

**Comment by yangfangfang1204** [comment]
`function handleFrame(frame) {
    console.log("after decode format:"+frame.format);
    ready_frames.push(frame);
    if (underflow) {
      underflow = false;
      setTimeout(renderFrame, 0);      
    }
  }`

the result is `after decode format:null`

**Comment by sandersdan** [comment]
If `format` is `null` then the frame doesn't have a defined format and `copyTo()` cannot function. You can still render it; `createImageBitmap()`, `drawImage()` and other `CanvasImageSource` APIs do not rely on the format.

You can expect `null` to be very rare starting in Chrome M96 (currently in beta).

If you're curious about the implementation details: depending on details of the graphics context, some kinds of frames may be accessed as different formats. Since WebCodecs frames can be passed between workers, it would be possible for the `format` to change. In these cases, Chrome disables `copyTo()` by returning `format = null`.
