### ISSUE TITLE
Moving codec registry to "Registry Track"

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#398]
This came up in today's WG call
https://www.w3.org/2021/11/09-mediawg-minutes.html#t03

From the call, it sounds like we need to adjust the status from NOTE-ED to something else (probably something like "registry report", but I don't find any similar status in bikeshed documentation. @tidoust also mentioned minor editorial changes. @tidoust can you outline next steps?

**Comment by chcunningham** [comment]
Also, just to be sure crystal clear, am I right that we're talking about the process changes introduced by this PR?
https://github.com/w3c/w3process/pull/335

**Comment by tidoust** [comment]
> From the call, it sounds like we need to adjust the status from NOTE-ED to something else (probably something like "registry report", but I don't find any similar status in bikeshed documentation

Bikeshed has not yet been updated to reflect the changes introduced in Process 2021. That's ongoing. We'll need to wait until that happens.

> Also, just to be sure crystal clear, am I right that we're talking about the process changes introduced by this PR?
w3c/w3process#335

Yes, there may have been further adjustments made to the text that are not part of this PR. The result is [The Registry Track](https://www.w3.org/2021/Process-20211102/#registries) section in the Process document.

**Comment by tidoust** [comment]
Status update:
- Group [resolved to switch document to Registry track](https://www.w3.org/2022/09/16-mediawg-minutes.html#r01) during TPAC's face-to-face
- Document was updated to meet process requirements related to registries, see #571 
- Switch requested and approved by W3C Director in https://github.com/w3c/transitions/issues/463
- Actual publication as Draft Registry under https://www.w3.org/TR/ should take place tomorrow (13 October 2022). I'll update and close this issue once done.
- Boilerplate updated in Bikeshed so that auto-publish can resume after tomorrow's publication: https://github.com/tabatkins/bikeshed-boilerplate/pull/26

**Comment by tidoust** [comment]
> Actual publication as Draft Registry under https://www.w3.org/TR/ should take place tomorrow (13 October 2022). I'll update and close this issue once done.

I failed to do that, but Draft Registry was indeed published at https://www.w3.org/TR/webcodecs-codec-registry/
Closing the issue accordingly :)
