### ISSUE TITLE
Custom codecs and protocols?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [w3c/webcodecs#413]
Hi,
Is webcodecs can alllow the developer to integrate easily new audio and video codecs for encode and decode?
with webtransport which is protocol agnostic, could the the stream frames be carried with custom protocol too?
thanks

**Comment by dalecurtis** [comment]
Kind of but not really anymore than you could today. A developer could implement the WebCodecs interfaces with their own codecs in WASM or JS. I think what you're thinking of is more something like a "decoder worklet" or "encoder worklet" that would let you plug WASM or JS into our native encoding and decoding stacks.

**Comment by ROBERT-MCDOWELL** [comment]
yes, like a webcodecs plugin API that let the developer to encode decode with the codec of his choice.

**Comment by sandersdan** [comment]
This was considered in the early design of WebCodecs but is currently considered out of scope.

To integrate with browser media pipelines would require something like a codec worklet, but current worklet definitions do not support multithreading and provide limited guarantees about state preservation. This is likely to be overly restrictive.

For decode, the shortest path to an integration would be buffering decoded frames with MSE. Given the latency and memory constraints there I'm not sure if that's all that much more useful than the existing MediaStreamTrack integration.

I'm going to close this since there are no plans to work on it in the near term, but I would be interested in any specific proposals that could overcome the problems or suggest which other web platform working groups we should be seeking support from.

**Comment by ROBERT-MCDOWELL** [comment]
thanks sandersdan for your explaination. It would be nice if such interest will grow. for now MediaStreamTrack is indeed a good (restricted) choice.

**Comment by padenot** [comment]
> To integrate with browser media pipelines would require something like a codec worklet, but current worklet definitions do not support multithreading and provide limited guarantees about state preservation. This is likely to be overly restrictive.

The purpose of Worklets is to be minimal and to be extended to precisely match the best possible setup for a particular task. Any kind of threading and any kind of state management can be added on top (see the very specific setup for `AudioWorkletProcessor`, that has both).

**Comment by sandersdan** [comment]
> see the very specific setup for AudioWorkletProcessor, that has both

`AudioWorkletGlobalScope` is very restrictive and includes no methods for spawning threads. It is true that `AudioWorkletNode` guarantees that the scope is retained as long as it is active

**Comment by padenot** [comment]
Yes, it's a very specific setup, as in it runs on a real-time thread, and periodically from an OS level callback.

The point being that any setup that is be useful is possible for Worklets.
