### ISSUE TITLE
How to keep decoder alive in a video editor?

### ISSUE THREAD

**Issue by breakingsword** [w3c/webcodecs#424]
I have a video editor web app want to use webcodec.
but when I try , I find chrome will relaim decoders that are inactive.
User may pause video and do edit video or sth. when user begin to play, decoder has been relaimed.
I want to know how to keep this decoder alive?

**Comment by sandersdan** [comment]
There is no way to guarantee that a codec is available forever; it could be reclaimed due to resource pressure, the loss of a graphics context, or other reasons. I would recommend that WebCodecs applications implement recovery mechanisms such as seek-to-previous keyframe to recover from decoder loss. Unlike for `<video>`, this isn't something that can be hidden because the browser cannot force a WebCodecs application to provide a keyframe.

All that said, the Chrome implementation is currently strict about reclamation, and we are actively working to find the best set of tradeoffs. You can follow https://bugs.chromium.org/p/chromium/issues/detail?id=1277618 to see progress on that effort. You can also pass `--disable-features=ReclaimInactiveWebCodecs` if that simplifies your development process.

**Comment by breakingsword** [comment]
您好，我是周峰。您的邮件我已收到，我会尽快回复。

**Comment by chcunningham** [comment]
In addition to the [pressure-based reclamation](https://bugs.chromium.org/p/chromium/issues/detail?id=1277618) Dan mentioned, we are exploring whether we can [always disable reclamation for foreground windows](https://bugs.chromium.org/p/chromium/issues/detail?id=1279707) (looks promising).

**Comment by breakingsword** [comment]
thanks a lot
