### ISSUE TITLE
VideoFrame.copy()

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#436]
The core idea is to be able to make a copy of a `VideoFrame` that can be held indefinitely without blocking decoding. Dev's can achieve similar today using `createImageBitmap()` (see discussion in #382). 

In many cases this would be "deep copy", so considerably more resource intensive than a `clone()`. ​I'm not firm on the name `copy()`... I don't hate it, but I don't know if it hints well at the distinction from `clone()`. Maybe `deepCopy()`...

**Comment by chcunningham** [comment]
> Dev's can achieve similar today using `createImageBitmap()` (see discussion in #382). 

@sandersdan, do we expect `copy()` to enable performance gains over `createImageBitmap()`, or is it just about having a more intuitive API?

**Comment by chcunningham** [comment]
> @sandersdan, do we expect copy() to enable performance gains over createImageBitmap(), or is it just about having a more intuitive API?

Thinking on it more, I guess createImageBitmap() would imply a conversion to RGB, so it's a bit more expensive than a simple copy. I'm not sure if the conversion always happens right away though (e.g. maybe if you never ask for ImageData the conversion could be avoided).

**Comment by yangfangfang1204** [comment]
is there a demo that how to use `VideoFrame.copy()` ?

And What is the return of the `VideoFrame.copy()` ? Is it a shared texture index or shared texture data?

**Comment by srubenacker** [comment]
I wanted to add one more advantage for VideoFrame.copy() over createImageBitmap().  In the use case of copying VideoFrames into a cache, I believe the yuv420/nv12 frame would be a 50% memory savings compared to the RGB ImageBitmap.

**Comment by hlevring** [comment]
This seems like a super useful feature, so wanted to check if there might have been some further internal discussions around moving this forward?

**Comment by Djuffin** [comment]
More or less functionality should be achievable with this code:

```js
async function cloneFrame(prototype_frame) {
  let size = prototype_frame.allocationSize();
  let buf = new ArrayBuffer(size);
  let layout = await prototype_frame.copyTo(buf);
  let init = {
    format: prototype_frame.format,
    timestamp: prototype_frame.timestamp,
    codedWidth: prototype_frame.visibleRect.width,
    codedHeight: prototype_frame.visibleRect.height,
    displayWidth: prototype_frame.displayWidth,
    displayHeight: prototype_frame.displayHeight,    
    colorSpace: prototype_frame.colorSpace,
    layout: layout,
    transfer: [buf]
  };
  return new VideoFrame(buf, init);
}
```

**Comment by hlevring** [comment]
Yeah sure that works, but the issue with that approach is that it copies frames to CPU memory.  There should really be a way to copy a frame without moving it from the device where it resides. Obviously not a good idea to keep a lot of frames on GPU without a lot of memory, but there cases where we want or need to keep of buffer of a few handfuls of frames (without changing layout), which is more than what GPU decode buffer may allow without complaining.

**Comment by shamaniThrall** [comment]
I think Wecodecs are designed to have full access over the decoding process for special implementations. When i need just simple default behaviour a video tag with a mediasoucre buffer is enough in the most cases.
One typicall "special" application is playing H264 backwards. With Webcodecs this is nearly NOT possible. You have to decode a full GOP lets say 15 frames I, P0.. P14 and then, when decoded, play them backwards (maybe with setintervall) p14,p13,p12...I and while playing we have time to decode the GOP before the currently playing gop, so that we can go from one GOP the previous one smoothly ..I, P14 .... But for this we need 2 Gops completly decoded .in memory. Atm there is NO performent way to play backwards smoothly .
I sse two different approaches atm:
a) copy each decoded frame (with frame.copy()) to system  memory and copy it back to a VideoFrame when it should be displayed -> not a good idea like hlevring mentioned allready
b) decode on the fly, hold just a small buffer (let say 8 frames decoded, i dunno how many frames the decoder allows to be opened at a time, in my test i can hold 10 frames open, but is this alwas so?). Then split the 8 frames into two buffers of 4 frames, the time we are playing 4 decoded frames we can decode the prev 4 frames. But this results in a unnessary decoding work , because we had to decoded the Gop multiple time 
I.. P14 to hold P14..P11 in our buffer,
I..P10 to get P10..P6,while playing P14..P11
I..P5, to get P5..P1 while playing P10..P6
I
=> especially the decoding expensiv i frame must be decoded 4 times in this approch => that makes no sense @ all

And sorry guys, in times where the smallest graphic card has gigabytes of memory, i think there is NO reason to not allocate 30 frames directly on the gpu side. So an API change is definitely a good idea. I would suggest 2 changes 
a) implement a frame.gpuclone(): VideoFrame that creates a deep clone of frame. so that the frame for the decode can be released 
b) pass a param numVideoFrames?: number in the VideoDecoderConfig, to specify the number of Videoframes that the decoder may allocate and that could be opened parallel

**Comment by padenot** [comment]
Nothing in the Web Codecs specification say you can't have 30 frames allocated on the GPU side, or generally keep 30 `VideoFrame` around. Case in point, you can do it on some implementations, and shipped web applications do it already. If a particular implementation doesn't allow it, please file an issue on their tracker:

- WebKit (Safari): https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Media (WebKit bugzilla account needed).
- Blink (Chrome): https://new.crbug.com/ (Google account needed).
- Gecko (Firefox): https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Audio%2FVideo%3A%20WebCodecs (GitHub or Mozilla Bugzilla account needed).
