### ISSUE TITLE
AudioData timestamp and duration should be nullable

### ISSUE THREAD

**Issue by tguilbert-google** [w3c/webcodecs#503]
`videoFrame.duration` and `videoFrame.timestamp` are both nullable.

For symmetry, `audioData.duration` and `audioData.timestamp` should also be nullable.

This also prevents receiving a valid timestamp after closing the `audioData`.

**Comment by onthegit** [comment]
Does this relate to https://github.com/w3c/webcodecs/issues/502 ?

**Comment by tguilbert-google** [comment]
It doesn't. This is just for consistency of the API, discovered while working on a [Chromium implementation issue](https://crbug.com/1338935)

**Comment by chcunningham** [comment]
https://github.com/w3c/webcodecs/pull/437 would make `videoFrame.timestamp` non-nullable. The PR is mostly ready, just languishing due to other priorities (and vacation). 

`videoFrame.duration` would remain nullable though. We could make `AudioData.duration` nullable to match, but it's a little weird to make that change because `AudioData.duration` is a [computed value](https://w3c.github.io/webcodecs/#dom-audiodata-duration) that should never be `null`.

**Comment by tguilbert-google** [comment]
I am ok with `audioData.duration` being non-nullable. It at least returns 0 after closure, which is a good indicator that the data is closed. It's also a value that cannot be attained otherwise (the AudioData constructor throws if ever we try to pass in 0 frames)

If `videoFrame.timestamp` is becoming non-nullable, leaving `audioData.timestamp` as is seems fine to me. It is still odd to me that a closed AudioData will still returns their pre-closure timestamps. Returning a timestamp of 0 (like duration does) doesn't seem viable, since 0 is a valid timestamp.

**Comment by padenot** [comment]
We're probably not going to do this because we're going to merge #437.

**Comment by tguilbert-google** [comment]
That seems good.

AudioData still returns its initial value after it is closed. Are we still ok with this? Considering that a duration of 0 would indicate that the AudioData object is closed.

I prefer returning the original timestamp than returning 0.

**Comment by padenot** [comment]
Same.
