### ISSUE TITLE
HEVC Registration

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#504]
There is interest in using HEVC with WebCodecs, so HEVC registration would be a good idea. 

PR in progress: https://github.com/w3c/webcodecs/pull/499

**Comment by lishulincug** [comment]
Webcodes support codec h265 ？
[test](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/issues/16)

**Comment by aboba** [comment]
Not yet, but [AV1 encoding is supported](https://webrtc.internaut.com/wc/wcWorker/).

**Comment by exolution** [comment]
but chrome canary already support h265

**Comment by wenerme** [comment]
@exolution any source ?

**Comment by yisibl** [comment]
See: https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding

```
open /Applications/Google\ Chrome\ Canary.app --args --enable-features=PlatformHEVCDecoderSupport
```

**Comment by sandersdan** [comment]
It is not intended for HEVC to work with current Chrome, but it does seem that it's not explicitly blocked, and the decoder selection  does succeed with that flag. As there is no explicit HEVC code in our WebCodecs implementation, `hvcC` is not handled, and therefore only Annex B is operable.

Closing this issue as completed since the spec proposal is committed.

**Comment by lishulincug** [comment]
I implemented a test page code for rosbag. edge and chrome canary is supported。
https://intelligenttransportation.gitee.io/webcodes/rosbagPlayerWeb.html
