### ISSUE TITLE
VideoColorSpace: enum to replace nullable boolean?

### ISSUE THREAD

**Issue by tidoust** [w3c/webcodecs#592]
The [`VideoColorSpace`](https://w3c.github.io/webcodecs/#videocolorspace) interface has a nullable boolean attribute `fullRange`. That means the attribute actually captures 3 states: `null`, `false`, `true`. Using a boolean to capture 3 states does not seem like good practice, as developers will collate the first two cases if they write code such as:

```js
if (!colorSpace.fullRange) {
  // ...
}
```

Wouldn't an enum be preferrable?

For what it's worth, there are 3 other occurrences of nullable booleans in web specs: [`ProximitySensor.near`](https://w3c.github.io/proximity/#proximity-sensor-interface), [`RTCPeerConnection.canTrickleIceCandidates`](https://w3c.github.io/webrtc-pc/#webidl-175960107), [`XRCompositionLayer.chromaticAberrationCorrection`](https://immersive-web.github.io/layers/#xrcompositionlayertype). They could also benefit from using an enum.

**Comment by sandersdan** [comment]
I don't think so; the states are true, false, and unspecified, with unspecified being rare or even aberrant. It's actually probably for the best if null and false are collated since non-full-range is the most common interpretation.

There are ways of specifying the range that include more categories; internally Chrome splits unspecified into invalid vs derived. There is always a correct value to use that is either true or false, though.

**Comment by dalecurtis** [comment]
Dan's points are correct, so closing this.
