### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by reinhrst** [w3c/webcodecs#643]
I'm trying to feed a newly created VideoDecoder an EncodedVideoChunk. The result I get (in Chrome 110) is (for `new VideoDecoder({...., error: error=> console.log(error)})`:
`DOMException: Decoding error.`

First of all, I think it should not be a `DOMException`.

Secondly, the error "Decoding error" is very unhelpful. I understand that it's hard to give specific errors, but some more information could be helpful.

**Comment by dalecurtis** [comment]
We can't provide more specific details in the error message for fingerprinting reasons, but https://developer.chrome.com/docs/devtools/media-panel/ or chrome://media-internals will usually have more detailed error information.

If that's still not the case we file a new bug a https://crbug.com/new to track whats happening here (since this tracker is for browser-agnostic / spec issues)

**Comment by reinhrst** [comment]
Very useful feedback, these places helped me a lot!

For the next person coming here: it actually helped (and could have saved me 100 hours ;)) to switch off hardware acceleration for video decoding. Without HA, it all decodes well. ([Chromium bug posted](https://bugs.chromium.org/p/chromium/issues/detail?id=1420714))
