### ISSUE TITLE
Sporadic build failures 

### ISSUE THREAD

**Issue by Djuffin** [w3c/webcodecs#782]
Spec build process fails sporadically on different registry entries.
Retry usually helps.

```
  [INFO] Finding shortName for Bikeshed document: video_frame_metadata_registry.src.html
    Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!
```

Examples:
https://github.com/w3c/webcodecs/actions/runs/8335174561/job/22810156792
https://github.com/w3c/webcodecs/actions/runs/8150577505/job/22277066608?pr=775
https://github.com/w3c/webcodecs/actions/runs/8267058031/job/22616549305

**Comment by Djuffin** [comment]
@tidoust Do you by any chance know what might be causing it?
I've heard webrtc spec had similar issues.

**Comment by tidoust** [comment]
Note the first failure is unrelated: publication failed because the job started on 18 March right *before* midnight, generated a document whose date was 18 March, but then submitted the generated spec for publication to /TR right *after* midnight, so on 19 March, and the publication rules checker wants the document date to match the current date. I'll report it to see whether that check could be made a bit more lax!

I'll look into the other two. They signal that the Puppeteer instance used to load the spec failed to start within 30s. The timeout could probably be increased, but then there should be no reason for that instance creation to take more than a few seconds...

**Comment by aboba** [comment]
@Djuffin @padenot   Is the problem resolved now?  If so, can we close this?

**Comment by Djuffin** [comment]
I think so, I triggered a run and it went smoothly. 
https://github.com/w3c/webcodecs/actions/runs/9007463213
