### ISSUE TITLE
VideoPixelFormat enum values do not follow casing rule guidelines

### ISSUE THREAD

**Issue by domenic** [w3c/webcodecs#786]
That is, per https://w3ctag.github.io/design-principles/#casing-rules, you should have things like `"rgba"` instead of `"RGBA"`.

I suspect this is too late to change. (Is that right?) If so, then adding a note explaining that this is a historical mistake to the spec would be helpful.

**Comment by Djuffin** [comment]
Yeah, at least 3 UAs already implemented the spec and many websites use it. 
We can't rename these enums simply because of non conformity to casing rules. 

As for the note about a historical mistake, who would be the target audience for such a note in the spec? I think neither web developers nor browser implementers care about the origins of this naming.

**Comment by domenic** [comment]
> As for the note about a historical mistake, who would be the target audience for such a note in the spec?

People performing review, such as myself in an API owners role, or the W3C TAG. I've also heard many complaints from web developers about inconsistent casing across various web specs (although not yet this one in particular), so I suspect they would find it helpful as well.

**Comment by domenic** [comment]
It's disappointing that this was closed as "won't fix", as it will make future reviews harder.
