### ISSUE TITLE
decode an EncodedVideoChunk to produce multiple frames

### ISSUE THREAD

**Issue by ruofeng618** [w3c/webcodecs#822]
I discovered that when using VideoDecoder to process H.264 data, if I set hardwareAcceleration: "prefer-hardware", the output produces 20 identical frames even though I only decode one EncodedVideoChunk. But set hardwareAcceleration: "prefer-software".it does not happen Why is this happening?

**Comment by sandersdan** [comment]
This doesn't sound like a specification issue. If you are reporting a bug in a browser implementation, please use the bug tracker for that browser. Otherwise, the Discussions tab would be better.

That said, there is not enough information here to assist. A reproduction case is probably necessary to investigate fully. My best guess is that your input chunk contains multiple frames.
